# Site settings
title: richim96 - Web Portfolio
description: A minimalist website written in Ruby.

# User settings
username: Riccardo Mei
user_title: software engineer
user_description: >
  Monday to Friday, I tell computers what to do for money. On the weekends, I tell computers what to do for fun.
  I have experience building backend services, intelligent systems, AI regulation, E2E data pipelines.
  I work as a backend engineer in a leading Berlin startup.
  ğŸ“ Based in Berlin, Germany.
linkedin_username: rmei96
github_username:  richim96

exclude: ['package.json', 'node_modules', 'vendor']
